### ISSUE TITLE
Issues with 0.7.2 package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/magic_enum#2]
I took a look at the queued 0.7.2 package and I see a few issues that you may want to fix before I publish it:

1. Since this library's header installs directly into `include` (e.g., `/usr/include/`), it's probably best not to provide `version.hpp` since installing it into this location is bound to clash (if you do want to keep it, then another option is to rename it, for example, to `magic_enum_version.hpp` and move it to `include/` next to `magic_enum.hpp`).

2. The way you setup header installation is not the best. Currently, `version.hpp` ends up in the root of the installation directory and `magic_enum.hpp` always in the `include/` subdirectory (even if the user overrides where the headers should be installed with `config.install.include`). The correct way to do it for this layout is:

```
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = false
}
```

Let me know if you would like to fix these and submit a revision for this version (see `bdep-release --revision`).

BTW, in the future, you may wan to consider using `bdep-new` to generate the more canonical skeleton for the layout used by the library (see [SOURCE LAYOUT](https://build2.org/bdep/doc/bdep-new.xhtml#src-layout)). For example, for this library it would be:

```
bdep new -l c++ -t lib,split,no-subdir,no-version,binless magic_enum
```

**Comment by Wmbat** [comment]
I will fix those 2 problems as soon as I can and I will submit a revision for this version

**Comment by Wmbat** [comment]
@boris-kolpackov I've run into a small problem when I updated the installation setup to 
```
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = false
}
```
The CI is now failing at the `test-installed` phase. https://ci.cppget.org/@f855697f-2467-4e06-b723-0b2fdff0f241?builds
It seems to be unable to find the `magic_enum.hpp` header. That was why I had originally changed the installation procedure.

Any idea on how to fix that?

**Comment by boris-kolpackov** [comment]
Yes, looking at the complete CI log I see the following line:

```
sudo install -m 644 magic_enum-0.7.2/magic_enum/include/magic_enum.hpp /opt/private/include/include
```

So it's clear you are still installing recreating subdirectories. And looking at your buildifle confirms it (you still have `install.subdirs = true`): https://github.com/build2-packaging/magic_enum/blob/0.7.2-revision/magic_enum/buildfile#L25
